apiVersion: user.zitadel.m.crossplane.io/v1alpha1
kind: Metadata
metadata:
  annotations:
    meta.upbound.io/example-id: user/v1alpha1/metadata
  labels:
    testing.upbound.io/example-name: default
  name: default
  namespace: crossplane-system
spec:
  forProvider:
    key: a_key
    orgIdSelector:
      matchLabels:
        testing.upbound.io/example-name: zitadel_org
    userIdSelector:
      matchLabels:
        testing.upbound.io/example-name: zitadel_human_user
    value: a_value
