// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
	kindref "github.com/crossplane/upjet/v2/pkg/resource/kindref"
)

type MemberInitParameters struct {

	// (Set of String) List of roles granted. Instance member roles must start with 'IAM_' (e.g., IAM_OWNER, IAM_OWNER_VIEWER). See https://zitadel.com/docs/guides/manage/console/administrators for available roles.
	// List of roles granted. Instance member roles must start with 'IAM_' (e.g., IAM_OWNER, IAM_OWNER_VIEWER). See https://zitadel.com/docs/guides/manage/console/administrators for available roles.
	// +listType=set
	Roles []*string `json:"roles,omitempty" tf:"roles,omitempty"`

	// (String) ID of the user
	// ID of the user
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-zitadel/apis/namespaced/user/v1alpha1.HumanUser
	// +crossplane:generate:reference:apiVersion=user.zitadel.m.crossplane.io/v1alpha1
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-zitadel/apis/namespaced/user/v1alpha1.MachineUser
	// +crossplane:generate:reference:apiVersion=user.zitadel.m.crossplane.io/v1alpha1
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`

	// Reference to a HumanUser in user (default) or MachineUser in user to populate userId.
	// Set kind, and apiVersion if kind alone is ambiguous, to choose a target other than the default.
	// +kubebuilder:validation:XValidation:rule="!has(self.kind) || self.kind in ['HumanUser', 'MachineUser']",message="kind must be one of HumanUser, MachineUser"
	// +kubebuilder:validation:XValidation:rule="!has(self.apiVersion) || (has(self.kind) && (self.apiVersion + '/' + self.kind) in ['user.zitadel.m.crossplane.io/v1alpha1/HumanUser', 'user.zitadel.m.crossplane.io/v1alpha1/MachineUser'])",message="apiVersion and kind must be one of: user.zitadel.m.crossplane.io/v1alpha1 HumanUser, user.zitadel.m.crossplane.io/v1alpha1 MachineUser"
	// +kubebuilder:validation:Optional
	UserIDRef *kindref.NamespacedReference `json:"userIdRef,omitempty" tf:"-"`

	// Selector for a HumanUser in user (default) or MachineUser in user to populate userId.
	// Set kind, and apiVersion if kind alone is ambiguous, to choose a target other than the default.
	// +kubebuilder:validation:XValidation:rule="!has(self.kind) || self.kind in ['HumanUser', 'MachineUser']",message="kind must be one of HumanUser, MachineUser"
	// +kubebuilder:validation:XValidation:rule="!has(self.apiVersion) || (has(self.kind) && (self.apiVersion + '/' + self.kind) in ['user.zitadel.m.crossplane.io/v1alpha1/HumanUser', 'user.zitadel.m.crossplane.io/v1alpha1/MachineUser'])",message="apiVersion and kind must be one of: user.zitadel.m.crossplane.io/v1alpha1 HumanUser, user.zitadel.m.crossplane.io/v1alpha1 MachineUser"
	// +kubebuilder:validation:Optional
	UserIDSelector *kindref.NamespacedSelector `json:"userIdSelector,omitempty" tf:"-"`
}

type MemberObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Set of String) List of roles granted. Instance member roles must start with 'IAM_' (e.g., IAM_OWNER, IAM_OWNER_VIEWER). See https://zitadel.com/docs/guides/manage/console/administrators for available roles.
	// List of roles granted. Instance member roles must start with 'IAM_' (e.g., IAM_OWNER, IAM_OWNER_VIEWER). See https://zitadel.com/docs/guides/manage/console/administrators for available roles.
	// +listType=set
	Roles []*string `json:"roles,omitempty" tf:"roles,omitempty"`

	// (String) ID of the user
	// ID of the user
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type MemberParameters struct {

	// (Set of String) List of roles granted. Instance member roles must start with 'IAM_' (e.g., IAM_OWNER, IAM_OWNER_VIEWER). See https://zitadel.com/docs/guides/manage/console/administrators for available roles.
	// List of roles granted. Instance member roles must start with 'IAM_' (e.g., IAM_OWNER, IAM_OWNER_VIEWER). See https://zitadel.com/docs/guides/manage/console/administrators for available roles.
	// +kubebuilder:validation:Optional
	// +listType=set
	Roles []*string `json:"roles,omitempty" tf:"roles,omitempty"`

	// (String) ID of the user
	// ID of the user
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-zitadel/apis/namespaced/user/v1alpha1.HumanUser
	// +crossplane:generate:reference:apiVersion=user.zitadel.m.crossplane.io/v1alpha1
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-zitadel/apis/namespaced/user/v1alpha1.MachineUser
	// +crossplane:generate:reference:apiVersion=user.zitadel.m.crossplane.io/v1alpha1
	// +kubebuilder:validation:Optional
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`

	// Reference to a HumanUser in user (default) or MachineUser in user to populate userId.
	// Set kind, and apiVersion if kind alone is ambiguous, to choose a target other than the default.
	// +kubebuilder:validation:XValidation:rule="!has(self.kind) || self.kind in ['HumanUser', 'MachineUser']",message="kind must be one of HumanUser, MachineUser"
	// +kubebuilder:validation:XValidation:rule="!has(self.apiVersion) || (has(self.kind) && (self.apiVersion + '/' + self.kind) in ['user.zitadel.m.crossplane.io/v1alpha1/HumanUser', 'user.zitadel.m.crossplane.io/v1alpha1/MachineUser'])",message="apiVersion and kind must be one of: user.zitadel.m.crossplane.io/v1alpha1 HumanUser, user.zitadel.m.crossplane.io/v1alpha1 MachineUser"
	// +kubebuilder:validation:Optional
	UserIDRef *kindref.NamespacedReference `json:"userIdRef,omitempty" tf:"-"`

	// Selector for a HumanUser in user (default) or MachineUser in user to populate userId.
	// Set kind, and apiVersion if kind alone is ambiguous, to choose a target other than the default.
	// +kubebuilder:validation:XValidation:rule="!has(self.kind) || self.kind in ['HumanUser', 'MachineUser']",message="kind must be one of HumanUser, MachineUser"
	// +kubebuilder:validation:XValidation:rule="!has(self.apiVersion) || (has(self.kind) && (self.apiVersion + '/' + self.kind) in ['user.zitadel.m.crossplane.io/v1alpha1/HumanUser', 'user.zitadel.m.crossplane.io/v1alpha1/MachineUser'])",message="apiVersion and kind must be one of: user.zitadel.m.crossplane.io/v1alpha1 HumanUser, user.zitadel.m.crossplane.io/v1alpha1 MachineUser"
	// +kubebuilder:validation:Optional
	UserIDSelector *kindref.NamespacedSelector `json:"userIdSelector,omitempty" tf:"-"`
}

// MemberSpec defines the desired state of Member
type MemberSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            MemberParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider MemberInitParameters `json:"initProvider,omitempty"`
}

// MemberStatus defines the observed state of Member.
type MemberStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        MemberObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Member is the Schema for the Members API. Resource representing the membership of a user on an instance, defined with the given role.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,zitadel}
type Member struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.roles) || (has(self.initProvider) && has(self.initProvider.roles))",message="spec.forProvider.roles is a required parameter"
	Spec   MemberSpec   `json:"spec"`
	Status MemberStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MemberList contains a list of Members
type MemberList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Member `json:"items"`
}

// Repository type metadata.
var (
	Member_Kind             = "Member"
	Member_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Member_Kind}.String()
	Member_KindAPIVersion   = Member_Kind + "." + CRDGroupVersion.String()
	Member_GroupVersionKind = CRDGroupVersion.WithKind(Member_Kind)
)

func init() {
	SchemeBuilder.Register(&Member{}, &MemberList{})
}
