// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type GrantInitParameters struct {

	// Reference to a HumanUser in user to populate userId.
	// +kubebuilder:validation:Optional
	HumanUserIDRef *v1.NamespacedReference `json:"humanUserIdRef,omitempty" tf:"-"`

	// Selector for a HumanUser in user to populate userId.
	// +kubebuilder:validation:Optional
	HumanUserIDSelector *v1.NamespacedSelector `json:"humanUserIdSelector,omitempty" tf:"-"`

	// (String) ID of the organization. If not provided, the organization of the authenticated user/service account is used.
	// ID of the organization. If not provided, the organization of the authenticated user/service account is used.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-zitadel/apis/namespaced/org/v1alpha1.Organization
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// Reference to a Organization in org to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDRef *v1.NamespacedReference `json:"orgIdRef,omitempty" tf:"-"`

	// Selector for a Organization in org to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDSelector *v1.NamespacedSelector `json:"orgIdSelector,omitempty" tf:"-"`

	// (String) ID of the granted project
	// ID of the granted project
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-zitadel/apis/namespaced/project/v1alpha1.Grant
	ProjectGrantID *string `json:"projectGrantId,omitempty" tf:"project_grant_id,omitempty"`

	// Reference to a Grant in project to populate projectGrantId.
	// +kubebuilder:validation:Optional
	ProjectGrantIDRef *v1.NamespacedReference `json:"projectGrantIdRef,omitempty" tf:"-"`

	// Selector for a Grant in project to populate projectGrantId.
	// +kubebuilder:validation:Optional
	ProjectGrantIDSelector *v1.NamespacedSelector `json:"projectGrantIdSelector,omitempty" tf:"-"`

	// (String) ID of the project
	// ID of the project
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-zitadel/apis/namespaced/project/v1alpha1.Project
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// (Set of String) List of roles granted
	// List of roles granted
	// +listType=set
	RoleKeys []*string `json:"roleKeys,omitempty" tf:"role_keys,omitempty"`

	// (String) ID of the user
	// ID of the user
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-zitadel/apis/namespaced/user/v1alpha1.HumanUser
	// +crossplane:generate:reference:refFieldName=HumanUserIDRef
	// +crossplane:generate:reference:selectorFieldName=HumanUserIDSelector
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type GrantObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) ID of the organization. If not provided, the organization of the authenticated user/service account is used.
	// ID of the organization. If not provided, the organization of the authenticated user/service account is used.
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// (String) ID of the granted project
	// ID of the granted project
	ProjectGrantID *string `json:"projectGrantId,omitempty" tf:"project_grant_id,omitempty"`

	// (String) ID of the project
	// ID of the project
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Set of String) List of roles granted
	// List of roles granted
	// +listType=set
	RoleKeys []*string `json:"roleKeys,omitempty" tf:"role_keys,omitempty"`

	// (String) ID of the user
	// ID of the user
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type GrantParameters struct {

	// Reference to a HumanUser in user to populate userId.
	// +kubebuilder:validation:Optional
	HumanUserIDRef *v1.NamespacedReference `json:"humanUserIdRef,omitempty" tf:"-"`

	// Selector for a HumanUser in user to populate userId.
	// +kubebuilder:validation:Optional
	HumanUserIDSelector *v1.NamespacedSelector `json:"humanUserIdSelector,omitempty" tf:"-"`

	// (String) ID of the organization. If not provided, the organization of the authenticated user/service account is used.
	// ID of the organization. If not provided, the organization of the authenticated user/service account is used.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-zitadel/apis/namespaced/org/v1alpha1.Organization
	// +kubebuilder:validation:Optional
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// Reference to a Organization in org to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDRef *v1.NamespacedReference `json:"orgIdRef,omitempty" tf:"-"`

	// Selector for a Organization in org to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDSelector *v1.NamespacedSelector `json:"orgIdSelector,omitempty" tf:"-"`

	// (String) ID of the granted project
	// ID of the granted project
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-zitadel/apis/namespaced/project/v1alpha1.Grant
	// +kubebuilder:validation:Optional
	ProjectGrantID *string `json:"projectGrantId,omitempty" tf:"project_grant_id,omitempty"`

	// Reference to a Grant in project to populate projectGrantId.
	// +kubebuilder:validation:Optional
	ProjectGrantIDRef *v1.NamespacedReference `json:"projectGrantIdRef,omitempty" tf:"-"`

	// Selector for a Grant in project to populate projectGrantId.
	// +kubebuilder:validation:Optional
	ProjectGrantIDSelector *v1.NamespacedSelector `json:"projectGrantIdSelector,omitempty" tf:"-"`

	// (String) ID of the project
	// ID of the project
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-zitadel/apis/namespaced/project/v1alpha1.Project
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// (Set of String) List of roles granted
	// List of roles granted
	// +kubebuilder:validation:Optional
	// +listType=set
	RoleKeys []*string `json:"roleKeys,omitempty" tf:"role_keys,omitempty"`

	// (String) ID of the user
	// ID of the user
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-zitadel/apis/namespaced/user/v1alpha1.HumanUser
	// +crossplane:generate:reference:refFieldName=HumanUserIDRef
	// +crossplane:generate:reference:selectorFieldName=HumanUserIDSelector
	// +kubebuilder:validation:Optional
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

// GrantSpec defines the desired state of Grant
type GrantSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            GrantParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider GrantInitParameters `json:"initProvider,omitempty"`
}

// GrantStatus defines the observed state of Grant.
type GrantStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        GrantObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Grant is the Schema for the Grants API. Resource representing the authorization given to a user directly, including the given roles.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,zitadel}
type Grant struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              GrantSpec   `json:"spec"`
	Status            GrantStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// GrantList contains a list of Grants
type GrantList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Grant `json:"items"`
}

// Repository type metadata.
var (
	Grant_Kind             = "Grant"
	Grant_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Grant_Kind}.String()
	Grant_KindAPIVersion   = Grant_Kind + "." + CRDGroupVersion.String()
	Grant_GroupVersionKind = CRDGroupVersion.WithKind(Grant_Kind)
)

func init() {
	SchemeBuilder.Register(&Grant{}, &GrantList{})
}
