// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0
// Code transformed by upjet. DO NOT EDIT.

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	apisresolver "github.com/crossplane-contrib/provider-upjet-zitadel/internal/apis"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	xpresource "github.com/crossplane/crossplane-runtime/v2/pkg/resource"
	kindref "github.com/crossplane/upjet/v2/pkg/resource/kindref"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

func (mg *AccessToken) ResolveReferences( // ResolveReferences of this AccessToken.
	ctx context.Context, c client.Reader) error {
	var m xpresource.Managed
	var l xpresource.ManagedList
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error
	{
		m, l, err = apisresolver.GetManagedResource("org.zitadel.crossplane.io", "v1alpha1", "Organization", "OrganizationList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.OrgID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.OrgIDRef,
			Selector:     mg.Spec.ForProvider.OrgIDSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.OrgID")
	}
	mg.Spec.ForProvider.OrgID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.OrgIDRef = rsp.ResolvedReference
	{
		m, l, err = apisresolver.GetManagedResource("user.zitadel.crossplane.io", "v1alpha1", "MachineUser", "MachineUserList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.UserID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.UserIDRef,
			Selector:     mg.Spec.ForProvider.UserIDSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.UserID")
	}
	mg.Spec.ForProvider.UserID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.UserIDRef = rsp.ResolvedReference
	{
		m, l, err = apisresolver.GetManagedResource("org.zitadel.crossplane.io", "v1alpha1", "Organization", "OrganizationList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.OrgID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.OrgIDRef,
			Selector:     mg.Spec.InitProvider.OrgIDSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.OrgID")
	}
	mg.Spec.InitProvider.OrgID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.OrgIDRef = rsp.ResolvedReference
	{
		m, l, err = apisresolver.GetManagedResource("user.zitadel.crossplane.io", "v1alpha1", "MachineUser", "MachineUserList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.UserID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.UserIDRef,
			Selector:     mg.Spec.InitProvider.UserIDSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.UserID")
	}
	mg.Spec.InitProvider.UserID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.UserIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Grant.
func (mg *Grant) ResolveReferences(ctx context.Context, c client.Reader) error {
	var m xpresource.Managed
	var l xpresource.ManagedList
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error
	{
		m, l, err = apisresolver.GetManagedResource("org.zitadel.crossplane.io", "v1alpha1", "Organization", "OrganizationList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.OrgID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.OrgIDRef,
			Selector:     mg.Spec.ForProvider.OrgIDSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.OrgID")
	}
	mg.Spec.ForProvider.OrgID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.OrgIDRef = rsp.ResolvedReference
	{
		m, l, err = apisresolver.GetManagedResource("project.zitadel.crossplane.io", "v1alpha1", "Grant", "GrantList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ProjectGrantID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.ProjectGrantIDRef,
			Selector:     mg.Spec.ForProvider.ProjectGrantIDSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ProjectGrantID")
	}
	mg.Spec.ForProvider.ProjectGrantID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ProjectGrantIDRef = rsp.ResolvedReference
	{
		m, l, err = apisresolver.GetManagedResource("project.zitadel.crossplane.io", "v1alpha1", "Project", "ProjectList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ProjectID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.ProjectIDRef,
			Selector:     mg.Spec.ForProvider.ProjectIDSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ProjectID")
	}
	mg.Spec.ForProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ProjectIDRef = rsp.ResolvedReference

	{
		ref := mg.Spec.ForProvider.UserIDRef.ToReference()
		sel := mg.Spec.ForProvider.UserIDSelector.ToSelector()
		apiVersion, kind := mg.Spec.ForProvider.UserIDRef.GetAPIVersion(), mg.Spec.ForProvider.UserIDRef.GetKind()
		// The selector chooses the target when it will select a new reference.
		if sel != nil && (ref == nil || sel.Policy.IsResolvePolicyAlways()) {
			apiVersion, kind = mg.Spec.ForProvider.UserIDSelector.GetAPIVersion(), mg.Spec.ForProvider.UserIDSelector.GetKind()
		}
		switch {
		case apiVersion == "" && kind == "", apiVersion == "" && kind == "HumanUser", apiVersion == "user.zitadel.crossplane.io/v1alpha1" && kind == "HumanUser":
			{
				m, l, err = apisresolver.GetManagedResource("user.zitadel.crossplane.io", "v1alpha1", "HumanUser", "HumanUserList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.UserID),
					Extract:      reference.ExternalName(),
					Namespace:    mg.GetNamespace(),
					Reference:    ref,
					Selector:     sel,
					To:           reference.To{List: l, Managed: m},
				})
			}
		case apiVersion == "" && kind == "MachineUser", apiVersion == "user.zitadel.crossplane.io/v1alpha1" && kind == "MachineUser":
			{
				m, l, err = apisresolver.GetManagedResource("user.zitadel.crossplane.io", "v1alpha1", "MachineUser", "MachineUserList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.UserID),
					Extract:      reference.ExternalName(),
					Namespace:    mg.GetNamespace(),
					Reference:    ref,
					Selector:     sel,
					To:           reference.To{List: l, Managed: m},
				})
			}
		default:
			err = errors.Errorf("unsupported reference target apiVersion %q, kind %q: must be one of: user.zitadel.crossplane.io/v1alpha1 HumanUser (default), user.zitadel.crossplane.io/v1alpha1 MachineUser", apiVersion, kind)
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.UserID")
		}
		mg.Spec.ForProvider.UserID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.UserIDRef = kindref.NewReference(apiVersion, kind, rsp.ResolvedReference)
	}
	{
		m, l, err = apisresolver.GetManagedResource("org.zitadel.crossplane.io", "v1alpha1", "Organization", "OrganizationList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.OrgID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.OrgIDRef,
			Selector:     mg.Spec.InitProvider.OrgIDSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.OrgID")
	}
	mg.Spec.InitProvider.OrgID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.OrgIDRef = rsp.ResolvedReference
	{
		m, l, err = apisresolver.GetManagedResource("project.zitadel.crossplane.io", "v1alpha1", "Grant", "GrantList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ProjectGrantID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.ProjectGrantIDRef,
			Selector:     mg.Spec.InitProvider.ProjectGrantIDSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ProjectGrantID")
	}
	mg.Spec.InitProvider.ProjectGrantID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ProjectGrantIDRef = rsp.ResolvedReference
	{
		m, l, err = apisresolver.GetManagedResource("project.zitadel.crossplane.io", "v1alpha1", "Project", "ProjectList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ProjectID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.ProjectIDRef,
			Selector:     mg.Spec.InitProvider.ProjectIDSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ProjectID")
	}
	mg.Spec.InitProvider.ProjectID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ProjectIDRef = rsp.ResolvedReference

	{
		ref := mg.Spec.InitProvider.UserIDRef.ToReference()
		sel := mg.Spec.InitProvider.UserIDSelector.ToSelector()
		apiVersion, kind := mg.Spec.InitProvider.UserIDRef.GetAPIVersion(), mg.Spec.InitProvider.UserIDRef.GetKind()
		// The selector chooses the target when it will select a new reference.
		if sel != nil && (ref == nil || sel.Policy.IsResolvePolicyAlways()) {
			apiVersion, kind = mg.Spec.InitProvider.UserIDSelector.GetAPIVersion(), mg.Spec.InitProvider.UserIDSelector.GetKind()
		}
		switch {
		case apiVersion == "" && kind == "", apiVersion == "" && kind == "HumanUser", apiVersion == "user.zitadel.crossplane.io/v1alpha1" && kind == "HumanUser":
			{
				m, l, err = apisresolver.GetManagedResource("user.zitadel.crossplane.io", "v1alpha1", "HumanUser", "HumanUserList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.UserID),
					Extract:      reference.ExternalName(),
					Namespace:    mg.GetNamespace(),
					Reference:    ref,
					Selector:     sel,
					To:           reference.To{List: l, Managed: m},
				})
			}
		case apiVersion == "" && kind == "MachineUser", apiVersion == "user.zitadel.crossplane.io/v1alpha1" && kind == "MachineUser":
			{
				m, l, err = apisresolver.GetManagedResource("user.zitadel.crossplane.io", "v1alpha1", "MachineUser", "MachineUserList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.UserID),
					Extract:      reference.ExternalName(),
					Namespace:    mg.GetNamespace(),
					Reference:    ref,
					Selector:     sel,
					To:           reference.To{List: l, Managed: m},
				})
			}
		default:
			err = errors.Errorf("unsupported reference target apiVersion %q, kind %q: must be one of: user.zitadel.crossplane.io/v1alpha1 HumanUser (default), user.zitadel.crossplane.io/v1alpha1 MachineUser", apiVersion, kind)
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.UserID")
		}
		mg.Spec.InitProvider.UserID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.UserIDRef = kindref.NewReference(apiVersion, kind, rsp.ResolvedReference)
	}

	return nil
}

// ResolveReferences of this HumanUser.
func (mg *HumanUser) ResolveReferences(ctx context.Context, c client.Reader) error {
	var m xpresource.Managed
	var l xpresource.ManagedList
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error
	{
		m, l, err = apisresolver.GetManagedResource("org.zitadel.crossplane.io", "v1alpha1", "Organization", "OrganizationList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.OrgID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.OrgIDRef,
			Selector:     mg.Spec.ForProvider.OrgIDSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.OrgID")
	}
	mg.Spec.ForProvider.OrgID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.OrgIDRef = rsp.ResolvedReference
	{
		m, l, err = apisresolver.GetManagedResource("org.zitadel.crossplane.io", "v1alpha1", "Organization", "OrganizationList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.OrgID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.OrgIDRef,
			Selector:     mg.Spec.InitProvider.OrgIDSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.OrgID")
	}
	mg.Spec.InitProvider.OrgID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.OrgIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Key.
func (mg *Key) ResolveReferences(ctx context.Context, c client.Reader) error {
	var m xpresource.Managed
	var l xpresource.ManagedList
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error
	{
		m, l, err = apisresolver.GetManagedResource("org.zitadel.crossplane.io", "v1alpha1", "Organization", "OrganizationList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.OrgID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.OrgIDRef,
			Selector:     mg.Spec.ForProvider.OrgIDSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.OrgID")
	}
	mg.Spec.ForProvider.OrgID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.OrgIDRef = rsp.ResolvedReference
	{
		m, l, err = apisresolver.GetManagedResource("user.zitadel.crossplane.io", "v1alpha1", "MachineUser", "MachineUserList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.UserID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.UserIDRef,
			Selector:     mg.Spec.ForProvider.UserIDSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.UserID")
	}
	mg.Spec.ForProvider.UserID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.UserIDRef = rsp.ResolvedReference
	{
		m, l, err = apisresolver.GetManagedResource("org.zitadel.crossplane.io", "v1alpha1", "Organization", "OrganizationList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.OrgID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.OrgIDRef,
			Selector:     mg.Spec.InitProvider.OrgIDSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.OrgID")
	}
	mg.Spec.InitProvider.OrgID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.OrgIDRef = rsp.ResolvedReference
	{
		m, l, err = apisresolver.GetManagedResource("user.zitadel.crossplane.io", "v1alpha1", "MachineUser", "MachineUserList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.UserID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.UserIDRef,
			Selector:     mg.Spec.InitProvider.UserIDSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.UserID")
	}
	mg.Spec.InitProvider.UserID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.UserIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this MachineUser.
func (mg *MachineUser) ResolveReferences(ctx context.Context, c client.Reader) error {
	var m xpresource.Managed
	var l xpresource.ManagedList
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error
	{
		m, l, err = apisresolver.GetManagedResource("org.zitadel.crossplane.io", "v1alpha1", "Organization", "OrganizationList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.OrgID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.OrgIDRef,
			Selector:     mg.Spec.ForProvider.OrgIDSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.OrgID")
	}
	mg.Spec.ForProvider.OrgID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.OrgIDRef = rsp.ResolvedReference
	{
		m, l, err = apisresolver.GetManagedResource("org.zitadel.crossplane.io", "v1alpha1", "Organization", "OrganizationList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.OrgID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.OrgIDRef,
			Selector:     mg.Spec.InitProvider.OrgIDSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.OrgID")
	}
	mg.Spec.InitProvider.OrgID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.OrgIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Metadata.
func (mg *Metadata) ResolveReferences(ctx context.Context, c client.Reader) error {
	var m xpresource.Managed
	var l xpresource.ManagedList
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error
	{
		m, l, err = apisresolver.GetManagedResource("org.zitadel.crossplane.io", "v1alpha1", "Organization", "OrganizationList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.OrgID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.OrgIDRef,
			Selector:     mg.Spec.ForProvider.OrgIDSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.OrgID")
	}
	mg.Spec.ForProvider.OrgID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.OrgIDRef = rsp.ResolvedReference

	{
		ref := mg.Spec.ForProvider.UserIDRef.ToReference()
		sel := mg.Spec.ForProvider.UserIDSelector.ToSelector()
		apiVersion, kind := mg.Spec.ForProvider.UserIDRef.GetAPIVersion(), mg.Spec.ForProvider.UserIDRef.GetKind()
		// The selector chooses the target when it will select a new reference.
		if sel != nil && (ref == nil || sel.Policy.IsResolvePolicyAlways()) {
			apiVersion, kind = mg.Spec.ForProvider.UserIDSelector.GetAPIVersion(), mg.Spec.ForProvider.UserIDSelector.GetKind()
		}
		switch {
		case apiVersion == "" && kind == "", apiVersion == "" && kind == "HumanUser", apiVersion == "user.zitadel.crossplane.io/v1alpha1" && kind == "HumanUser":
			{
				m, l, err = apisresolver.GetManagedResource("user.zitadel.crossplane.io", "v1alpha1", "HumanUser", "HumanUserList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.UserID),
					Extract:      reference.ExternalName(),
					Namespace:    mg.GetNamespace(),
					Reference:    ref,
					Selector:     sel,
					To:           reference.To{List: l, Managed: m},
				})
			}
		case apiVersion == "" && kind == "MachineUser", apiVersion == "user.zitadel.crossplane.io/v1alpha1" && kind == "MachineUser":
			{
				m, l, err = apisresolver.GetManagedResource("user.zitadel.crossplane.io", "v1alpha1", "MachineUser", "MachineUserList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.UserID),
					Extract:      reference.ExternalName(),
					Namespace:    mg.GetNamespace(),
					Reference:    ref,
					Selector:     sel,
					To:           reference.To{List: l, Managed: m},
				})
			}
		default:
			err = errors.Errorf("unsupported reference target apiVersion %q, kind %q: must be one of: user.zitadel.crossplane.io/v1alpha1 HumanUser (default), user.zitadel.crossplane.io/v1alpha1 MachineUser", apiVersion, kind)
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.UserID")
		}
		mg.Spec.ForProvider.UserID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.UserIDRef = kindref.NewReference(apiVersion, kind, rsp.ResolvedReference)
	}
	{
		m, l, err = apisresolver.GetManagedResource("org.zitadel.crossplane.io", "v1alpha1", "Organization", "OrganizationList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.OrgID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.OrgIDRef,
			Selector:     mg.Spec.InitProvider.OrgIDSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.OrgID")
	}
	mg.Spec.InitProvider.OrgID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.OrgIDRef = rsp.ResolvedReference

	{
		ref := mg.Spec.InitProvider.UserIDRef.ToReference()
		sel := mg.Spec.InitProvider.UserIDSelector.ToSelector()
		apiVersion, kind := mg.Spec.InitProvider.UserIDRef.GetAPIVersion(), mg.Spec.InitProvider.UserIDRef.GetKind()
		// The selector chooses the target when it will select a new reference.
		if sel != nil && (ref == nil || sel.Policy.IsResolvePolicyAlways()) {
			apiVersion, kind = mg.Spec.InitProvider.UserIDSelector.GetAPIVersion(), mg.Spec.InitProvider.UserIDSelector.GetKind()
		}
		switch {
		case apiVersion == "" && kind == "", apiVersion == "" && kind == "HumanUser", apiVersion == "user.zitadel.crossplane.io/v1alpha1" && kind == "HumanUser":
			{
				m, l, err = apisresolver.GetManagedResource("user.zitadel.crossplane.io", "v1alpha1", "HumanUser", "HumanUserList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.UserID),
					Extract:      reference.ExternalName(),
					Namespace:    mg.GetNamespace(),
					Reference:    ref,
					Selector:     sel,
					To:           reference.To{List: l, Managed: m},
				})
			}
		case apiVersion == "" && kind == "MachineUser", apiVersion == "user.zitadel.crossplane.io/v1alpha1" && kind == "MachineUser":
			{
				m, l, err = apisresolver.GetManagedResource("user.zitadel.crossplane.io", "v1alpha1", "MachineUser", "MachineUserList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.UserID),
					Extract:      reference.ExternalName(),
					Namespace:    mg.GetNamespace(),
					Reference:    ref,
					Selector:     sel,
					To:           reference.To{List: l, Managed: m},
				})
			}
		default:
			err = errors.Errorf("unsupported reference target apiVersion %q, kind %q: must be one of: user.zitadel.crossplane.io/v1alpha1 HumanUser (default), user.zitadel.crossplane.io/v1alpha1 MachineUser", apiVersion, kind)
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.UserID")
		}
		mg.Spec.InitProvider.UserID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.UserIDRef = kindref.NewReference(apiVersion, kind, rsp.ResolvedReference)
	}

	return nil
}
