// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type MetadataInitParameters_2 struct {

	// Reference to a HumanUser in user to populate userId.
	// +kubebuilder:validation:Optional
	HumanUserIDRef *v1.Reference `json:"humanUserIdRef,omitempty" tf:"-"`

	// Selector for a HumanUser in user to populate userId.
	// +kubebuilder:validation:Optional
	HumanUserIDSelector *v1.Selector `json:"humanUserIdSelector,omitempty" tf:"-"`

	// (String) The key of a metadata entry
	// The key of a metadata entry
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (String) ID of the organization. If not provided, the organization of the authenticated user/service account is used.
	// ID of the organization. If not provided, the organization of the authenticated user/service account is used.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-zitadel/apis/cluster/org/v1alpha1.Organization
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// Reference to a Organization in org to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDRef *v1.Reference `json:"orgIdRef,omitempty" tf:"-"`

	// Selector for a Organization in org to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDSelector *v1.Selector `json:"orgIdSelector,omitempty" tf:"-"`

	// (String) ID of the user
	// ID of the user
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-zitadel/apis/cluster/user/v1alpha1.HumanUser
	// +crossplane:generate:reference:refFieldName=HumanUserIDRef
	// +crossplane:generate:reference:selectorFieldName=HumanUserIDSelector
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`

	// (String) The string representation of a metadata entry value. For binary data, use the base64encode function.
	// The string representation of a metadata entry value. For binary data, use the base64encode function.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type MetadataObservation_2 struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The key of a metadata entry
	// The key of a metadata entry
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (String) ID of the organization. If not provided, the organization of the authenticated user/service account is used.
	// ID of the organization. If not provided, the organization of the authenticated user/service account is used.
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// (String) ID of the user
	// ID of the user
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`

	// (String) The string representation of a metadata entry value. For binary data, use the base64encode function.
	// The string representation of a metadata entry value. For binary data, use the base64encode function.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type MetadataParameters_2 struct {

	// Reference to a HumanUser in user to populate userId.
	// +kubebuilder:validation:Optional
	HumanUserIDRef *v1.Reference `json:"humanUserIdRef,omitempty" tf:"-"`

	// Selector for a HumanUser in user to populate userId.
	// +kubebuilder:validation:Optional
	HumanUserIDSelector *v1.Selector `json:"humanUserIdSelector,omitempty" tf:"-"`

	// (String) The key of a metadata entry
	// The key of a metadata entry
	// +kubebuilder:validation:Optional
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (String) ID of the organization. If not provided, the organization of the authenticated user/service account is used.
	// ID of the organization. If not provided, the organization of the authenticated user/service account is used.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-zitadel/apis/cluster/org/v1alpha1.Organization
	// +kubebuilder:validation:Optional
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// Reference to a Organization in org to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDRef *v1.Reference `json:"orgIdRef,omitempty" tf:"-"`

	// Selector for a Organization in org to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDSelector *v1.Selector `json:"orgIdSelector,omitempty" tf:"-"`

	// (String) ID of the user
	// ID of the user
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-zitadel/apis/cluster/user/v1alpha1.HumanUser
	// +crossplane:generate:reference:refFieldName=HumanUserIDRef
	// +crossplane:generate:reference:selectorFieldName=HumanUserIDSelector
	// +kubebuilder:validation:Optional
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`

	// (String) The string representation of a metadata entry value. For binary data, use the base64encode function.
	// The string representation of a metadata entry value. For binary data, use the base64encode function.
	// +kubebuilder:validation:Optional
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

// MetadataSpec defines the desired state of Metadata
type MetadataSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     MetadataParameters_2 `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider MetadataInitParameters_2 `json:"initProvider,omitempty"`
}

// MetadataStatus defines the observed state of Metadata.
type MetadataStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        MetadataObservation_2 `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Metadata is the Schema for the Metadatas API. Add a custom attribute to the user like the authenticating system. You can use this information in your actions.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,zitadel}
type Metadata struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.key) || (has(self.initProvider) && has(self.initProvider.key))",message="spec.forProvider.key is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.value) || (has(self.initProvider) && has(self.initProvider.value))",message="spec.forProvider.value is a required parameter"
	Spec   MetadataSpec   `json:"spec"`
	Status MetadataStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MetadataList contains a list of Metadatas
type MetadataList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Metadata `json:"items"`
}

// Repository type metadata.
var (
	Metadata_Kind             = "Metadata"
	Metadata_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Metadata_Kind}.String()
	Metadata_KindAPIVersion   = Metadata_Kind + "." + CRDGroupVersion.String()
	Metadata_GroupVersionKind = CRDGroupVersion.WithKind(Metadata_Kind)
)

func init() {
	SchemeBuilder.Register(&Metadata{}, &MetadataList{})
}
