// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
	kindref "github.com/crossplane/upjet/v2/pkg/resource/kindref"
)

type GrantMemberInitParameters struct {

	// (String) ID of the grant
	// ID of the grant
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-zitadel/apis/namespaced/project/v1alpha1.Grant
	GrantID *string `json:"grantId,omitempty" tf:"grant_id,omitempty"`

	// Reference to a Grant in project to populate grantId.
	// +kubebuilder:validation:Optional
	GrantIDRef *v1.NamespacedReference `json:"grantIdRef,omitempty" tf:"-"`

	// Selector for a Grant in project to populate grantId.
	// +kubebuilder:validation:Optional
	GrantIDSelector *v1.NamespacedSelector `json:"grantIdSelector,omitempty" tf:"-"`

	// (String) ID of the organization. If not provided, the organization of the authenticated user/service account is used.
	// ID of the organization. If not provided, the organization of the authenticated user/service account is used.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-zitadel/apis/namespaced/org/v1alpha1.Organization
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// Reference to a Organization in org to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDRef *v1.NamespacedReference `json:"orgIdRef,omitempty" tf:"-"`

	// Selector for a Organization in org to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDSelector *v1.NamespacedSelector `json:"orgIdSelector,omitempty" tf:"-"`

	// (String) ID of the project
	// ID of the project
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-zitadel/apis/namespaced/project/v1alpha1.Project
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// (Set of String) List of roles granted
	// List of roles granted
	// +listType=set
	Roles []*string `json:"roles,omitempty" tf:"roles,omitempty"`

	// (String) ID of the user
	// ID of the user
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-zitadel/apis/namespaced/user/v1alpha1.HumanUser
	// +crossplane:generate:reference:apiVersion=user.zitadel.m.crossplane.io/v1alpha1
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-zitadel/apis/namespaced/user/v1alpha1.MachineUser
	// +crossplane:generate:reference:apiVersion=user.zitadel.m.crossplane.io/v1alpha1
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`

	// Reference to a HumanUser in user (default) or MachineUser in user to populate userId.
	// Set kind, and apiVersion if kind alone is ambiguous, to choose a target other than the default.
	// +kubebuilder:validation:XValidation:rule="!has(self.kind) || self.kind in ['HumanUser', 'MachineUser']",message="kind must be one of HumanUser, MachineUser"
	// +kubebuilder:validation:XValidation:rule="!has(self.apiVersion) || (has(self.kind) && (self.apiVersion + '/' + self.kind) in ['user.zitadel.m.crossplane.io/v1alpha1/HumanUser', 'user.zitadel.m.crossplane.io/v1alpha1/MachineUser'])",message="apiVersion and kind must be one of: user.zitadel.m.crossplane.io/v1alpha1 HumanUser, user.zitadel.m.crossplane.io/v1alpha1 MachineUser"
	// +kubebuilder:validation:Optional
	UserIDRef *kindref.NamespacedReference `json:"userIdRef,omitempty" tf:"-"`

	// Selector for a HumanUser in user (default) or MachineUser in user to populate userId.
	// Set kind, and apiVersion if kind alone is ambiguous, to choose a target other than the default.
	// +kubebuilder:validation:XValidation:rule="!has(self.kind) || self.kind in ['HumanUser', 'MachineUser']",message="kind must be one of HumanUser, MachineUser"
	// +kubebuilder:validation:XValidation:rule="!has(self.apiVersion) || (has(self.kind) && (self.apiVersion + '/' + self.kind) in ['user.zitadel.m.crossplane.io/v1alpha1/HumanUser', 'user.zitadel.m.crossplane.io/v1alpha1/MachineUser'])",message="apiVersion and kind must be one of: user.zitadel.m.crossplane.io/v1alpha1 HumanUser, user.zitadel.m.crossplane.io/v1alpha1 MachineUser"
	// +kubebuilder:validation:Optional
	UserIDSelector *kindref.NamespacedSelector `json:"userIdSelector,omitempty" tf:"-"`
}

type GrantMemberObservation struct {

	// (String) ID of the grant
	// ID of the grant
	GrantID *string `json:"grantId,omitempty" tf:"grant_id,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) ID of the organization. If not provided, the organization of the authenticated user/service account is used.
	// ID of the organization. If not provided, the organization of the authenticated user/service account is used.
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// (String) ID of the project
	// ID of the project
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Set of String) List of roles granted
	// List of roles granted
	// +listType=set
	Roles []*string `json:"roles,omitempty" tf:"roles,omitempty"`

	// (String) ID of the user
	// ID of the user
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type GrantMemberParameters struct {

	// (String) ID of the grant
	// ID of the grant
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-zitadel/apis/namespaced/project/v1alpha1.Grant
	// +kubebuilder:validation:Optional
	GrantID *string `json:"grantId,omitempty" tf:"grant_id,omitempty"`

	// Reference to a Grant in project to populate grantId.
	// +kubebuilder:validation:Optional
	GrantIDRef *v1.NamespacedReference `json:"grantIdRef,omitempty" tf:"-"`

	// Selector for a Grant in project to populate grantId.
	// +kubebuilder:validation:Optional
	GrantIDSelector *v1.NamespacedSelector `json:"grantIdSelector,omitempty" tf:"-"`

	// (String) ID of the organization. If not provided, the organization of the authenticated user/service account is used.
	// ID of the organization. If not provided, the organization of the authenticated user/service account is used.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-zitadel/apis/namespaced/org/v1alpha1.Organization
	// +kubebuilder:validation:Optional
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// Reference to a Organization in org to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDRef *v1.NamespacedReference `json:"orgIdRef,omitempty" tf:"-"`

	// Selector for a Organization in org to populate orgId.
	// +kubebuilder:validation:Optional
	OrgIDSelector *v1.NamespacedSelector `json:"orgIdSelector,omitempty" tf:"-"`

	// (String) ID of the project
	// ID of the project
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-zitadel/apis/namespaced/project/v1alpha1.Project
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// Reference to a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDRef *v1.NamespacedReference `json:"projectIdRef,omitempty" tf:"-"`

	// Selector for a Project in project to populate projectId.
	// +kubebuilder:validation:Optional
	ProjectIDSelector *v1.NamespacedSelector `json:"projectIdSelector,omitempty" tf:"-"`

	// (Set of String) List of roles granted
	// List of roles granted
	// +kubebuilder:validation:Optional
	// +listType=set
	Roles []*string `json:"roles,omitempty" tf:"roles,omitempty"`

	// (String) ID of the user
	// ID of the user
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-zitadel/apis/namespaced/user/v1alpha1.HumanUser
	// +crossplane:generate:reference:apiVersion=user.zitadel.m.crossplane.io/v1alpha1
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-upjet-zitadel/apis/namespaced/user/v1alpha1.MachineUser
	// +crossplane:generate:reference:apiVersion=user.zitadel.m.crossplane.io/v1alpha1
	// +kubebuilder:validation:Optional
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`

	// Reference to a HumanUser in user (default) or MachineUser in user to populate userId.
	// Set kind, and apiVersion if kind alone is ambiguous, to choose a target other than the default.
	// +kubebuilder:validation:XValidation:rule="!has(self.kind) || self.kind in ['HumanUser', 'MachineUser']",message="kind must be one of HumanUser, MachineUser"
	// +kubebuilder:validation:XValidation:rule="!has(self.apiVersion) || (has(self.kind) && (self.apiVersion + '/' + self.kind) in ['user.zitadel.m.crossplane.io/v1alpha1/HumanUser', 'user.zitadel.m.crossplane.io/v1alpha1/MachineUser'])",message="apiVersion and kind must be one of: user.zitadel.m.crossplane.io/v1alpha1 HumanUser, user.zitadel.m.crossplane.io/v1alpha1 MachineUser"
	// +kubebuilder:validation:Optional
	UserIDRef *kindref.NamespacedReference `json:"userIdRef,omitempty" tf:"-"`

	// Selector for a HumanUser in user (default) or MachineUser in user to populate userId.
	// Set kind, and apiVersion if kind alone is ambiguous, to choose a target other than the default.
	// +kubebuilder:validation:XValidation:rule="!has(self.kind) || self.kind in ['HumanUser', 'MachineUser']",message="kind must be one of HumanUser, MachineUser"
	// +kubebuilder:validation:XValidation:rule="!has(self.apiVersion) || (has(self.kind) && (self.apiVersion + '/' + self.kind) in ['user.zitadel.m.crossplane.io/v1alpha1/HumanUser', 'user.zitadel.m.crossplane.io/v1alpha1/MachineUser'])",message="apiVersion and kind must be one of: user.zitadel.m.crossplane.io/v1alpha1 HumanUser, user.zitadel.m.crossplane.io/v1alpha1 MachineUser"
	// +kubebuilder:validation:Optional
	UserIDSelector *kindref.NamespacedSelector `json:"userIdSelector,omitempty" tf:"-"`
}

// GrantMemberSpec defines the desired state of GrantMember
type GrantMemberSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            GrantMemberParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider GrantMemberInitParameters `json:"initProvider,omitempty"`
}

// GrantMemberStatus defines the observed state of GrantMember.
type GrantMemberStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        GrantMemberObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// GrantMember is the Schema for the GrantMembers API. Resource representing the membership of a user on an granted project, defined with the given role.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,zitadel}
type GrantMember struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.roles) || (has(self.initProvider) && has(self.initProvider.roles))",message="spec.forProvider.roles is a required parameter"
	Spec   GrantMemberSpec   `json:"spec"`
	Status GrantMemberStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// GrantMemberList contains a list of GrantMembers
type GrantMemberList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GrantMember `json:"items"`
}

// Repository type metadata.
var (
	GrantMember_Kind             = "GrantMember"
	GrantMember_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: GrantMember_Kind}.String()
	GrantMember_KindAPIVersion   = GrantMember_Kind + "." + CRDGroupVersion.String()
	GrantMember_GroupVersionKind = CRDGroupVersion.WithKind(GrantMember_Kind)
)

func init() {
	SchemeBuilder.Register(&GrantMember{}, &GrantMemberList{})
}
